### ISSUE TITLE
Travis deploy to npm not working

### ISSUE THREAD

**Issue by danpaz** [danpaz/bodybuilder#148]
Thought I set everything up following the [docs](https://docs.travis-ci.com/user/deployment) but Travis isn't publishing to npm.

Tried to fix this in #146 but still seeing this message:

```
Skipping a deployment with the npm provider because this is not a tagged commit
```
https://travis-ci.org/danpaz/bodybuilder/jobs/263864244#L1450

Current [.travis.yml](https://github.com/danpaz/bodybuilder/blob/master/.travis.yml):
```yml
...
deploy:
  provider: npm
  email: daniel.pazsoldan@gmail.com
  api_key:
    secure: <key>
  on:
    tags: true
    repo: danpaz/bodybuilder
    branch: master
    node: '6.11.2'
```

Looking for ideas from anyone on how to get this working.
